name: CI

on:
  push:
    branches: [main, master, develop, feature/**]
  pull_request:
    branches: [main, master, develop, feature/**]

env:
  PYTHON_VERSION: '3.10'

jobs:
  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run flake8
      run: flake8 src/ tests/

    - name: Check black formatting
      run: black --check src/ tests/

    - name: Run mypy
      run: mypy src/

    - name: Run tests
      run: pytest
